main: fi.melondia.pixeli.melondiaeffects.MelondiaEffects
version: 1.1
name: MelondiaEffects
depend: [ProtocolLib]

commands:
  meffect1:
    description: Nothing To Show
  meffect2:
    description: Nothing To Show
  vip:
    description: Nothing To Show